=== frankfloating/web-L1/SITE_bacar_mahamoud_abdou_frank_leggett/XML/auteurs.dtd
<!--contributeurs : Bacar Mahamoud Abdou, Frank Leggett-->

<!ELEMENT auteur (nom, citation?, mouvement_litteraire?, quelques_oeuvres, biographie, source, image*)>
<!ATTLIST auteur
    id ID #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom
    id ID #REQUIRED>

<!ELEMENT citation (#PCDATA)>
<!ATTLIST citation
    id ID #REQUIRED>

<!ELEMENT mouvement_litteraire (#PCDATA)>
<!ATTLIST mouvement_litteraire
    mouv CDATA #REQUIRED
    siecle CDATA #IMPLIED>

<!ELEMENT quelques_oeuvres (titre, odate, resume)+>
<!ATTLIST quelques_oeuvres
    id ID #REQUIRED>

<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre
    id ID #REQUIRED>

<!ELEMENT odate (#PCDATA)>
<!ATTLIST odate
    id ID #REQUIRED>

<!ELEMENT resume (#PCDATA)>
<!ATTLIST resume
    id ID #REQUIRED>

<!ELEMENT biographie (bdates+|#PCDATA)>
<!ATTLIST biographie
    id ID #REQUIRED>

<!ELEMENT bdates (#PCDATA)>
<!ATTLIST bdates
    id ID #REQUIRED>

<!ELEMENT source (#PCDATA)>
<!ATTLIST source
    id ID #REQUIRED>

<!ELEMENT image EMPTY>
<!ATTLIST image
    src CDATA #REQUIRED
    alt CDATA #REQUIRED
    ref CDATA #IMPLIED>

=== frankfloating/web-L1/SITE_bacar_mahamoud_abdou_frank_leggett/XML/auteurs_uklg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auteur SYSTEM "auteurs.dtd">
<!--contributeur : frank leggett-->
<auteur id="uklg-a">
    <nom id="uklg-n">Ursula Kroeber Le Guin</nom>
    <citation id="uklg-c">“What sane person could live in this world and not be crazy?”</citation>
    <mouvement_litteraire mouv="contemp">contemporain</mouvement_litteraire>
    <quelques_oeuvres id="uklg-o">
        <titre id="uklg-o1-t">Les Dépossédés</titre>
        <odate id="uklg-o1-d">1974</odate>
        <resume id="uklg-o1-r">Shevek, physicien de la lune Annares, se heurte à des obstacles en présentant ses idées. Cependant, Annares est une société anarchiste, le scientifique cherche alors à exposer ses idées au monde extérieur.</resume>
        <titre id="uklg-o2-t">La main gauche de la nuit</titre>
        <odate id="uklg-o2-d">1969</odate>
        <resume id="uklg-o2-r">Genly Aï, diplomate, est envoyé sur Nivôse pour convaincre la planète de rejoindre l'alliance interplanétaire. Mais le gouvernement auquel il a affaire, est antagoniste à cette idée. Il voyage alors à travers la planète d'être androgyne. </resume>
    </quelques_oeuvres>
    <biographie id="uklg-b">
        <bdates id="uklg-bd-n">née 21 octobre 1929</bdates>
        <bdates id="uklg-bd-d">mort 22 janvier 2018</bdates>
        née d'un anthropologue célèbre, elle fait ses études à Radcliff College puis Columbia University. Elle publie son premier roman en 1966: le monde de Rocannon. Elle utilise l'anthropologie dans ses travaux.
    </biographie>
    <source id="uklg-s">
        Britannica online encyclopedia
    </source>
    <image src="uklg1.jpg" alt="By Gorthian - Own work, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=31670340"/>
</auteur>

=== frankfloating/web-L1/SITE_bacar_mahamoud_abdou_frank_leggett/XML/auteurs_acc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auteur SYSTEM "auteurs.dtd">
<!--contributeur : frank leggett-->
<auteur id="acc-a">
    <nom id="acc-n">Arthur C. Clarke</nom>
    <quelques_oeuvres id="acc-o">
        <titre id="acc-o1-t">Rendez-vous avec Rama</titre>
        <odate id="acc-o1-d">1973</odate>
        <resume id="acc-o1-r">
            Un cylindre géant entre dans notre système solaire. Un groupe d'explorateur est envoyé pour sonder l'intérieur, mais ne trouve aucune vie. Seul des automates s'y trouve...
        </resume>
        <titre id="acc-o2-t">Childhood's end</titre>
        <odate id="acc-o2-d">1953</odate>
        <resume id="acc-o2-r">
            Des extraterrestre font leurs apparitions sur terre, ils ont l'apparence de demons. Ils se nomment comme seigneurs de la planète, mais laissent les humains continuer leurs affaires. Seulement, plus d'un siècle après leur apparition, les enfants humains évoluent en un esprit collectif pour rejoindre le seigneur des esprits. Ce dernier est un esprit collectif, les seigneurs étant leurs vassaux. Homo sapiens sapiens cesse d'exister.
        </resume>
    </quelques_oeuvres>
    <biographie id="acc-b">
        <bdates id="acc-b-b">née 16 décembre 1917</bdates>
        <bdates id="acc-b-d">mort 19 mars 2008</bdates>
        Auditeur pour le gouvernement britannique de 1936 à 1941, il devient instructeur radar durant la seconde guerre mondiale. Vendant ses histoires courtes dès 1946 à des magazines de sciences-fictions, il obtient une licence en sciences de King's College. Il écrit le script pour 2001, l'Odyssée de l'espace et en 1969, il entérine sa réputation en commentant l'atterrissage lunaire en 1969. Il meurt à Colombo au Sri-Lanka.
    </biographie>
    <source id="acc-s">
        Britannica online encyclopedia
    </source>
    <image src="acc1.jpg" alt="By ITU Pictures - https://www.flickr.com/photos/itupictures/16636142906, CC BY 2.0, https://commons.wikimedia.org/w/index.php?curid=64344486"/>
    <image src="acc2.jpg" alt="By en:User:Mamyjomarash (Amy Marash) - en:Image:Clarke sm.jpg, Public Domain, https://commons.wikimedia.org/w/index.php?curid=3736477"/>
</auteur>

=== frankfloating/web-L1/SITE_bacar_mahamoud_abdou_frank_leggett/XML/auteurs_vh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auteur SYSTEM "auteurs.dtd">

<!--Contributeur : Bacar MAHAMOUD ABDOU -->

<auteur id="vh-a">
    <nom id="vh-n">Victor Hugo</nom>
    <citation id="vh-c">
        “Detruire la misere ! Oui, cela est possible. Les législateur et les gouvernants doivent y songer sans cesse;
        car, en pareille matiere, tant que le possible n'est pas fait, le devoir n'est pas rempli.”

        "Je donne cinquante mille francs aux pauvres.
        Je desire etre porte au cimetiere avec leur corbillard.
        Je refuse l'oraison de toutes les eglises; je demande une priere àa toutes les ames.
        Je crois en Dieu"

        "Tout parle. Et maintenant, homme, sais-tu pourquoi
        Tout parles ? Ecoute bien. C'est que vents, ondes, flammes ,
        Arbres, roseaux, rochers, tout vit !
        Tout est plein d'ames."
    </citation>
    <mouvement_litteraire mouv="vh-mouv">Romantisme français</mouvement_litteraire>
    <quelques_oeuvres id="vh-o">
        <titre id="vh-o1-con">Les Contemplations</titre>
        <odate id="vh-o1-d"> 1856</odate>
        <resume id="vh-o1-r">
            " Les contemplations " est un recueil de poeme divisé en deux groupe qui sont: Autrefois (1830 - 1843) et Aujourd'hui (1843 - 1855).
            Cela est un recueil, dit, du souvenir, de l'amour, de la joie mais aussi de la mort, du deuil et même d'une certaine foi mystique.
            Ce recueil est eglement un hommage a sa fille Leopoldine Hugo, morte noyée dans la Seine à Villequier.
            Chaque partie contient, respectivement, trois chapitres.
        </resume>
        <titre id="vh-o2-pm">Pauca Meae</titre>
        <odate id="vh-o2-d">1856</odate>
        <resume id="vh-o2-r">
            Pauca meae est le livre IV des " Contemplation ", écrit par Victor Hugo après la mort de sa fille Léopoldine.
            Le titre se traduit par (quelque mots à ma fille).
            On y trouve en particulier le poème, célébre, ["Pure innocence! Vertu sainte..., 15 février 1843, 4 septembre 1843.....Demain dès l'aube, Mors, Charles Vacquerie"].
        </resume>
        <titre id="vh-o3-dda">Demain Dès L'Aube</titre>
        <odate id="vh-o3-d">1856</odate>
        <resume id="vh-o3-r">
            Composé de trois quatrins d'alexandrins en rimes croisées, ce court poème n'a pas de titre.
            De ce fait, on le surnomme par son incipit. C'est les premiers mots qui le composent.
            Il est celui-ci, le XIVeme poeme de Pauca Meae, le livre quatre des contemplations dans la seconde partie intitulée "Aujourd'hui 1843 - 1855".
            Le poeme est écrit tel un discours entre le narrateur et un interlocuteur inconnus, lui racontant à la premiere personne et au futur;
            comment il compte partir le lendemain dès l'aube et sans jamais être distrait par son environnement.
            Il s'y rendra en marchand à travers la campagne pour le rejoindre. Ce voyage s'avère être plus tragique que prévu, puisque le poème revele que cette personne chère est en faite morte.
            le narrateur se rend au cimetière pour fleurir sa tombe.
        </resume>
    </quelques_oeuvres>
    <biographie id="vh-b">
        <bdates id="vh-bd-n">né le 26 fev. 1802</bdates>
        <bdates id="vh-bd-d">mort le 22 mai 1885</bdates>
        Victor hugo, de son vrai nom Victor Marie Hugo, est un poète, dramaturge, écrivain, dessinateur romantique français et romancier.
        Il est, pour le monde, l'un des plus importants écrivains de la langue française. Il occupera une place des plus important dans l'histoire des lettres françaises au XIX siecle.
        Son oeuvre poétique comprends de nombreuses recueils de poemes lyriques. Il est également le poète engagé contre Napoléon III dans " Les Châtiments ", paru en 1853.
        Il est un poète épique dans "La Légende Des Siècles ", paru entre 1859 et 83.
        Il a rencontré un grand succès populaire comme romancier, d'abord avec "Notre-Dame De Paris " en 81 et encore plus encore avec " Les Misérables " en 1862.
        Ayant fortement contribué au changement et à l'amélioration de la poésie et du théâtre et, de plus, ayant marqué son époque par ses prises de position politiques sociale;
        Victor Hugo est encore célébré aujourd'hui, en France et à l'etrangers. Il est représenté tel un personnage illustre, dont la vie et l'oeuvre ont fait l'objet de nombreuses commentaires et hommages.
    </biographie>
    <image src="/Images/vh2.jpg" alt="https://www.edition-originale.com/media/h-3000-hugo_victor_les-contemplations_1856_edition-originale_2_46254.JPG"/>
</auteur>

=== frankfloating/web-L1/SITE_bacar_mahamoud_abdou_frank_leggett/XML/auteurs_na.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auteur SYSTEM "auteurs.dtd">

<auteur id="na-a">
    <nom id="na-n">Nassur Attoumani</nom>
    <citation id="na-c">“Dans un foyer, toutes les grandes décisions doivent être prises par la femme et toutes les dépenses faites par le mari. C’est ça, la vraie égalité.”</citation>
    <mouvement_litteraire mouv="na-mouv">Le Nouveau Roman (XXeme siecle)</mouvement_litteraire>
    <quelques_oeuvres id="na-o">
        <titre id="na-o1-lfdp">La fille du polygamme</titre>
        <odate id="na-o1-d">1974</odate>
        <resume id="na-01-r">
            Une fille peu instruite, pleine de volonté, va tout chambouler dans sa vie et celle de ses parents.
            Pleinement amoureuse d'un etranger, Fatiha Bahouili, epouse cet homme contre le gré de ses parents.
            Ici, le lecteur est au centre de la piece. tout est expose : l'immigration clandestine, la justice française, l'eternel machisme....
        </resume>
        <titre id="na-o2-trmmv">Tonton Rend Moi Ma Virginité</titre>
        <odate id="na-o2-d">2015</odate>
        <resume id="na-02-r">
            l'histoire debute dans un contexte à la brousse mahoraise. Une petite fille qui venait de fêter ses 10 ans, perd son pere quelques jours plus tard. Elle est faite orpheline du jour au lendemain, tandis qu'elle ne quittait jamais son père.
            Cette disparution lui est tellement insupportable, invivable qu'elle ne quitte presque jamais la chambre de sa mère. Un jour, elle surprend une conversation qui va chambouler toute sa vie.
            "Peut-il y avoir une simillitude entre une vieille voiture et une jeune fille violée ?".
        </resume>
    </quelques_oeuvres>
    <biographie id="na-b">
        <bdates id="na-dn">3 mai 2000</bdates>

            Ne à Moroni ( COMORES ), il est un dramaturge, un ecrivain et musicien français residant a Mayotte.
            Il etudiera au Comores avant de pouvoir faire ses annees college à Mayotte. Il etudiera au college de Dzaoudzi ( petit-terre ).
            Il repartira ensuite à Moroni pour le lycée ( Saïd-Mohamed6cheik ). Lorsque les Comores font la demande de leur independance, les lyceens sont envoyés à la Reunion.
            Il sera donc, etudiant au lycée Rolland-Garros où il decrochera un bac littéraire. en 1977, il va faire des études d'anglais à l' U.E.R d'Orléans.
            A l'obtention de son diplôme, il retourne à Mayotte, en 1983, pour enseigner le français et l'anglais au collège.
            Vers les années 2002, il organise des échanges entres les services culturels de Moroni et de sa région ( Sada ), où il est directeur de ma MJC ( maison des jeunes et des cultures).
            Il y découvrit la plupart de ses vocations musicales et littéraires aux alentours des années 80. Son premier sketch lui sera inspiré par la perte d'un membre de son groupe de musique quand un accident de voiture.
            Son objectif, denoncer les mefaits, les agissement, en mal, de la société mahoraise. En amoureux des arts, il se poduira sur la scene avec des themes théâtrales qui rassemblent humour et satire sur un fond musical.
            " La Fille Du Polygame " verra le jour en 1989. Ses oeuvres étant toujours engagés, ils traitent des sujet dites " controversés, tel que la polygamie, le viol ou encore l'inceste.

    </biographie>
    <image src="/Images/na1.jpg" alt="https://revueprojectiles.files.wordpress.com/2019/11/nasattoumani1.jpg"/>
</auteur>
